spring:
#  cloud:
#    loadbalancer:
#      retry:
#        enabled: true # default true
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: scott
    password: tiger
    driver-class-name: oracle.jdbc.driver.OracleDriver
    dbcp2:
      initial-size: 7
      max-total: 20
      pool-prepared-statements: true

sample:
  data:  local server config data
  data2: sample data 입니다.
  
github:
  cloneBaseDir: /tmp1
  token: f4d24eed3909ad8766e29fd2500e80cb33d153a82  