spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: scott
    password: tiger
    driver-class-name: oracle.jdbc.driver.OracleDriver
    dbcp2:
      initial-size: 7
      max-total: 20
      pool-prepared-statements: true


server:
  port: 8083
  additionalPorts: 8081,8082
  #ssl 인증서
  ssl-port: 8443
  key-store: C:/Users/vanddang/bahn_keystore.jks
  key-store-password: "!q2w3e4r"
  key-password: "!q2w3e4r"
  key-alias: bahn
  trust-store: C:/Users/vanddang/bahn_keystore_ts.ts
  trust-store-password: "!q2w3e4r"
  
management:
  endpoints:
    web:
      exposure:
        include: refresh, info, env, health, loggers, metrics, routes, filters

# Hystrix circuitBreaker
hystrix:
  command:
    default:    # command key. use 'default' for global setting.
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000   # default 1,000ms, Ribbon의 각 timeout보다 커야 기대하는대로 동작함
      circuitBreaker:
        requestVolumeThreshold: 10   # Minimum number of request to calculate circuit breaker's health. default 20
        errorThresholdPercentage: 100 # Error percentage to open circuit. default 50

nsbizmem-service:
  ribbon:
    NIWSServerListClassName: com.netflix.loadbalancer.ConfigurationBasedServerList
    eureka:
      enabled: false
    listOfServers: 127.0.0.1:8080
    ServerListRefreshInterval: 10000
    ConnectTimeout: 3000
    ReadTimeout: 5000

nsbizmem-service-dw:
  ribbon:
    NIWSServerListClassName: com.netflix.loadbalancer.ConfigurationBasedServerList
    eureka:
      enabled: false
    listOfServers: 127.0.0.1:8080
    ServerListRefreshInterval: 10000
    ConnectTimeout: 3000
    ReadTimeout: 5000
    
nsbizmem-service-certkey:
  ribbon:
    NIWSServerListClassName: com.netflix.loadbalancer.ConfigurationBasedServerList
    eureka:
      enabled: false
    listOfServers: 127.0.0.1:8080
    ServerListRefreshInterval: 10000
    ConnectTimeout: 3000
    ReadTimeout: 5000
        
zuul:
  ignoredPatterns: /actuator/**
  routes:
      nsbizmem-service: /**