spring:
  profiles: dev
sample: dev 안녕하세요.

hystrix:
  command:
    default:    # command key. use 'default' for global setting.
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1000   # default 1,000ms
      circuitBreaker:
        requestVolumeThreshold: 2   # Minimum number of request to calculate circuit breaker's health. default 20
        errorThresholdPercentage: 100 # Error percentage to open circuit. default 50
    service1: # sample service name
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1000   # default 1,000ms
      circuitBreaker:
        requestVolumeThreshold: 8   # Minimum number of request to calculate circuit breaker's health. default 20
        errorThresholdPercentage: 100 # Error percentage to open circuit. default 50


---

  
spring:
  profiles: stg
sample: stg 안녕하세요.


---

spring:
  profiles: real
sample: real 안녕하세요.???  