spring:
  application:
    name: nsess-config-server
  
--- #local
spring:
  profiles: local
  cloud:
    config:
      server:
        git:
          uri: https://bitbucket.skbroadband.com/scm/dt/nsess-config-server.git #default repository
          searchPaths: '*'
          repos:
            nsess:
              pattern: nsess-* #yml file pattern
              cloneOnStart: true
              force-pull: true
              uri: https://github.com/vanddang/nsess-config-server.git
              searchPaths: nsess* #yml file directory, *:하위 디렉토리 포함
              username: bjban
              password: a1234567890
              #ignoreLocalSshSettings: true
              #hostKey: someHostKey
              #hostKeyAlgorithm: ssh-rsa
              #strictHostKeyChecking: true
              #privateKey: |
server:
  port: 8888
          
          

--- #dev
spring:
  profiles: dev
server:
  port: 8888     
          
          
          
--- #stg
spring:
  profiles: stg
server:
  port: 8888      
          

          
--- #prod
spring:
  profiles: prod
server:
  port: 8888