--- #local
spring:
  profiles: local
  security:
    user:
      name: skbconfigserveradmin
      password: '!skbconfigserveradmin'
  cloud:
    config:
      server:
        git:
          uri: https://bitbucket.skbroadband.com/scm/dt/nsess-config-server.git #default repository
          searchPaths: '*'
          repos:
            nsess:
              pattern: nsess-* #yml file pattern
              cloneOnStart: true
              force-pull: true
              uri: https://bitbucket.skbroadband.com/scm/dt/nsess-config-server.git
              searchPaths: nsess* #yml file directory, *:하위 디렉토리 포함
              username: bjban # git 공통 계정 확인필요
              password: a1234567890 # git 공통 계정 패스워드 확인필요
server:
  port: 8888
          
          

--- #dev
spring:
  profiles: dev
server:
  port: 8888     
          
          
          
--- #stg
spring:
  profiles: stg
server:
  port: 8888      
          

          
--- #prod
spring:
  profiles: prod
server:
  port: 8888