server:
  port: 8888
  
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/vanddang/oksusu-config-server
          #username: vanddang@gmail.com
          #password: tkfkdgo83#