spring:
  application:
    name: nsess-config-server
    
    
--- #local
spring:
  profiles: local
  cloud:
    config:
      server:
        git:
          uri: https://bitbucket.skbroadband.com/scm/dt/nsess-config-server.git
          searchPaths: gateway, nsbizmem
          #username: bjban@bdinc.co.kr
          #password: a1234567890111
          #basedir: nsess
server:
  port: 8888
          
          

--- #dev
spring:
  profiles: dev
  cloud:
    config:
      server:
        git:
          uri: https://bitbucket.skbroadband.com/scm/dt/nsess-config-server.git
          #basedir: nsess
server:
  port: 8888          
          
          
          
--- #stg
spring:
  profiles: stg
  cloud:
    config:
      server:
        git:
          uri: https://bitbucket.skbroadband.com/scm/dt/nsess-config-server.git
          #basedir: nsess
server:
  port: 8888          
          

          
--- #prod
spring:
  profiles: prod
  cloud:
    config:
      server:
        git:
          uri: https://bitbucket.skbroadband.com/scm/dt/nsess-config-server.git
          #basedir: nsess
server:
  port: 8888