server:
  port: 8888
  
spring:
  profiles:
    active: dev
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/vanddang/oksusu-config-server
          #username: vanddang@gmail.com
          #password: tkfkdgo83#