spring:
  application:
    name: nsess-config-server
    
--- #local
spring:
  profiles: local
  cloud:
    config:
      server:
        git:
          uri: https://bitbucket.skbroadband.com/scm/dt/nsess-config-server.git #default repository
          searchPaths: nsess
          repos:
            nsbizmem:
              pattern: 'nsbizmem*' #yml file pattern
              uri: https://bitbucket.skbroadband.com/scm/dt/nsess-config-server.git
              searchPaths: nsbizmem* #yml file directory, *:하위 디렉토리 포함
            gateway:
              pattern: 'gateway*'
              uri: https://github.com/vanddang/nsess-config-server.git
              searchPaths: gateway*              
server:
  port: 8888
          
          

--- #dev
spring:
  profiles: dev
  cloud:
    config:
      server:
        git:
          uri: https://bitbucket.skbroadband.com/scm/dt/nsess-config-server.git #default repository
          searchPaths: nsess
          repos:
            nsess:
              pattern: 'nsess*' #yml file pattern
              uri: https://bitbucket.skbroadband.com/scm/dt/nsess-config-server.git
              searchPaths: nsess* #yml file directory, *:하위 디렉토리 포함
server:
  port: 8888     
          
          
          
--- #stg
spring:
  profiles: stg
  cloud:
    config:
      server:
        git:
          uri: https://bitbucket.skbroadband.com/scm/dt/nsess-config-server.git #default repository
          searchPaths: nsess
          repos:
            nsess:
              pattern: 'nsess*' #yml file pattern
              uri: https://bitbucket.skbroadband.com/scm/dt/nsess-config-server.git
              searchPaths: nsess* #yml file directory, *:하위 디렉토리 포함
server:
  port: 8888      
          

          
--- #prod
spring:
  profiles: prod
  cloud:
    config:
      server:
        git:
          uri: https://bitbucket.skbroadband.com/scm/dt/nsess-config-server.git #default repository
          searchPaths: nsess
          repos:
            nsess:
              pattern: 'nsess*' #yml file pattern
              uri: https://bitbucket.skbroadband.com/scm/dt/nsess-config-server.git
              searchPaths: nsess* #yml file directory, *:하위 디렉토리 포함
server:
  port: 8888