server:
  port: 8888
  
spring:
  application:
    name: nsess-config-server
  cloud:
    config:
      server:
        git:
          uri: https://bitbucket.skbroadband.com/scm/dt/nsess-config-server.git